#!/usr/bin/env python3
"""Validate that a feature is ready to advance to a target phase.

For each target phase, check that the prerequisite artifacts exist, contain
the required sections, have no `[TO BE FILLED]` stub markers, and (for the
two human gates) carry an APPROVED decision.

Usage:
    python scripts/validate_phase.py <feature_path> <target_phase>

target_phase: research | spec | plan | plan-review | tasks | implement |
              verify | review | ship

Exit codes:
  0   ready to advance
  1   unexpected error
  10  not ready (validation failed)
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

VALID_PHASES = [
    "research",
    "spec",
    "plan",
    "plan-review",
    "tasks",
    "implement",
    "verify",
    "review",
    "ship",
]

# Required sections (markdown headers) per artifact, used to detect stubs.
REQUIRED_SECTIONS: dict[str, list[str]] = {
    "research.md": [
        "## Summary",
        "## Relevant Files",
        "## Existing Patterns",
        "## Dependencies & Impact",
        "## Constraints & Risks",
    ],
    "spec.md": [
        "## Problem Statement",
        "## Goals",
        "## Non-Goals",
        "## Acceptance Criteria",
    ],
    "plan.md": [
        "## Architecture Approach",
        "## Implementation Phases",
        "## Testing Strategy",
        "## Constitution Compliance",
    ],
    "plan-review.md": [
        "## Decision",
    ],
    "tasks.md": [
        "## Task",
    ],
    "verify.md": [
        "## Verification Report",
    ],
    "review.md": [
        "## Acceptance Criteria",
        "## Decision",
    ],
    "ship.md": [
        "## Summary",
        "## Delivery Checklist",
    ],
}

# What artifacts must be valid before advancing to each phase.
# (greenfield should not gate on research.md — handled by --greenfield flag)
PREREQUISITES: dict[str, list[str]] = {
    "research": [],  # entering research needs no prior artifact
    "spec": [],  # research.md only required for brownfield (caller decides)
    "plan": ["spec.md"],
    "plan-review": ["spec.md", "plan.md"],
    "tasks": ["spec.md", "plan.md", "plan-review.md"],
    "implement": ["spec.md", "plan.md", "plan-review.md", "tasks.md"],
    "verify": ["spec.md", "plan.md", "plan-review.md", "tasks.md"],
    "review": ["spec.md", "plan.md", "plan-review.md", "tasks.md", "verify.md"],
    "ship": [
        "spec.md",
        "plan.md",
        "plan-review.md",
        "tasks.md",
        "verify.md",
        "review.md",
    ],
}


@dataclass
class Result:
    ok: bool
    passed: list[str] = field(default_factory=list)
    failed: list[str] = field(default_factory=list)
    exit_code: int = 0

    def add_pass(self, msg: str) -> None:
        self.passed.append(msg)

    def add_fail(self, msg: str) -> None:
        self.failed.append(msg)
        self.ok = False
        if self.exit_code == 0:
            self.exit_code = 10


def is_stub(text: str) -> bool:
    """Detect a stub: very short or contains TO BE FILLED markers."""
    if "[TO BE FILLED]" in text:
        return True
    # Stub files generated by new_feature.py are < 5 non-empty lines.
    non_empty = [ln for ln in text.splitlines() if ln.strip()]
    return len(non_empty) < 5


def has_required_sections(text: str, sections: list[str]) -> list[str]:
    missing = [s for s in sections if s not in text]
    return missing


def has_approved_decision(text: str) -> bool:
    """Look for APPROVED in a checked checkbox or a Decision line."""
    # Check for `[x] ✅ APPROVED` or similar
    pattern = re.compile(
        r"\[\s*x\s*\][^\n]*APPROVED(?!-WITH-CHANGES)",
        re.IGNORECASE,
    )
    return bool(pattern.search(text))


def validate_artifact(feature_path: Path, filename: str, result: Result) -> None:
    f = feature_path / filename
    if not f.exists():
        result.add_fail(f"{filename}: missing")
        return
    text = f.read_text(encoding="utf-8")
    if is_stub(text):
        result.add_fail(f"{filename}: still a stub (no real content)")
        return
    sections = REQUIRED_SECTIONS.get(filename, [])
    missing = has_required_sections(text, sections)
    if missing:
        result.add_fail(
            f"{filename}: missing required sections: {', '.join(missing)}"
        )
        return

    # Special: gates must be APPROVED.
    if filename == "plan-review.md":
        if not has_approved_decision(text):
            result.add_fail(
                "plan-review.md: decision is not APPROVED "
                "(must be Phase 4 Human Gate #1)"
            )
            return
    if filename == "review.md":
        if not has_approved_decision(text):
            result.add_fail(
                "review.md: decision is not APPROVED "
                "(must be Phase 8 Human Gate #2)"
            )
            return

    result.add_pass(f"{filename}: ok")


def validate_phase(feature_path: Path, target_phase: str) -> Result:
    result = Result(ok=True)

    if target_phase not in VALID_PHASES:
        result.add_fail(
            f"unknown target phase '{target_phase}'. "
            f"Valid: {', '.join(VALID_PHASES)}"
        )
        return result

    if not feature_path.exists() or not feature_path.is_dir():
        result.add_fail(f"feature path does not exist: {feature_path}")
        return result

    prereqs = PREREQUISITES[target_phase]
    if not prereqs:
        result.add_pass(f"phase '{target_phase}' has no prerequisites")
        return result

    for filename in prereqs:
        validate_artifact(feature_path, filename, result)

    return result


def self_verify() -> None:
    """Internal config consistency check. Raises AssertionError on failure."""
    # Every valid phase must have a prerequisite list (possibly empty).
    for phase in VALID_PHASES:
        assert phase in PREREQUISITES, f"VALID_PHASES/{phase} missing in PREREQUISITES"
    # Every prerequisite must reference an artifact we know how to validate.
    for phase, prereqs in PREREQUISITES.items():
        for filename in prereqs:
            assert filename in REQUIRED_SECTIONS, (
                f"PREREQUISITES[{phase}] references {filename} but it has no "
                f"REQUIRED_SECTIONS entry"
            )
    # The two human gates must be enforced before any downstream phase.
    for phase in ("tasks", "implement", "verify", "review", "ship"):
        assert "plan-review.md" in PREREQUISITES[phase], (
            f"phase '{phase}' must require plan-review.md (Phase 4 gate)"
        )
    for phase in ("ship",):
        assert "review.md" in PREREQUISITES[phase], (
            f"phase '{phase}' must require review.md (Phase 8 gate)"
        )


def main() -> int:
    try:
        self_verify()
    except AssertionError as exc:
        print(f"ERROR: internal config check failed: {exc}", file=sys.stderr)
        return 1

    parser = argparse.ArgumentParser(
        description="Validate a feature is ready to advance to a target phase."
    )
    parser.add_argument(
        "feature_path",
        help="Path to feature dir, e.g. .sdd/features/001-google-sso/",
    )
    parser.add_argument(
        "target_phase",
        choices=VALID_PHASES,
        help="Target phase to advance to",
    )
    args = parser.parse_args()

    feature_path = Path(args.feature_path).resolve()

    try:
        result = validate_phase(feature_path, args.target_phase)
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: unexpected failure: {exc}", file=sys.stderr)
        return 1

    print(f"Validating readiness for phase: {args.target_phase}")
    print(f"Feature: {feature_path}")
    print()

    if result.passed:
        print("Passed checks:")
        for p in result.passed:
            print(f"  ok  {p}")
    if result.failed:
        print("Failed checks:")
        for f in result.failed:
            print(f"  !!  {f}")

    print()
    if result.ok:
        print(f"READY → can advance to {args.target_phase}")
        return 0
    print(f"NOT READY → cannot advance to {args.target_phase}")
    return result.exit_code


if __name__ == "__main__":
    sys.exit(main())
